spring:
  application:
    # \uD504\uB85C\uC81D\uD2B8 \uC774\uB984
    name: total_jpa_back

  datasource:
    # MySQL \uB4DC\uB77C\uC774\uBC84
    driver-class-name: com.mysql.cj.jdbc.Driver

    # DB \uC5F0\uACB0 \uC8FC\uC18C
    url: jdbc:mysql://localhost:3306/total_jpa

    # \uD658\uACBD\uBCC0\uC218 DB_USER \uC5C6\uC73C\uBA74 root \uC0AC\uC6A9
    username: ${DB_USER:root}

    # \uD658\uACBD\uBCC0\uC218 DB_PW \uC5C6\uC73C\uBA74 1111 \uC0AC\uC6A9
    password: ${DB_PW:1111}

  jpa:
    hibernate:
      # \uC2E4\uD589 \uC2DC \uD14C\uC774\uBE14 \uC790\uB3D9 \uC5C5\uB370\uC774\uD2B8
      # create : \uC2E4\uD589\uB9C8\uB2E4 \uC0C8\uB85C \uC0DD\uC131
      # update : \uBCC0\uACBD\uC0AC\uD56D\uB9CC \uBC18\uC601
      # validate : \uC5D4\uD2F0\uD2F0\uC640 \uD14C\uC774\uBE14 \uAC80\uC99D
      # none : \uC0AC\uC6A9 \uC548\uD568
      ddl-auto: validate

    properties:
      hibernate:
        # \uC2E4\uD589 SQL \uCD9C\uB825
        show_sql: true

        # SQL \uC608\uC058\uAC8C \uCD9C\uB825
        format_sql: true

    # MySQL \uBC29\uC5B8 \uC124\uC815
    database-platform: org.hibernate.dialect.MySQLDialect
    # JPA \uD14C\uC774\uBE14\uC744 \uC0DD\uC131\uD55C \uD6C4\uC5D0 data.sql\uC744 \uC2E4\uD589\uD574\uB77C
    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always  # data.sql\uC744 \uD56D\uC0C1 \uC2E4\uD589

  autoconfigure:
    exclude:
      # \uC2A4\uD504\uB9C1 \uC2DC\uD050\uB9AC\uD2F0 \uAE30\uBCF8 \uB85C\uADF8\uC778 \uBE44\uD65C\uC131\uD654
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  level:
    # \uBC14\uC778\uB529 \uD30C\uB77C\uBBF8\uD130 \uCD9C\uB825
    org.hibernate.orm.jdbc.bind: trace